server:
  port: 8081

spring:
  application:
    name: incubator-wazx-uaa
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wazx?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false&requireSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 3000000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    password: foobared
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: d256961b-b317-403b-b93f-1210340b1327

# keytool -genkey -alias wazx-jwt -storepass bccfcsuknfxmecbh -keyalg RSA -keysize 2048 -keystore wazx-jwt-store.jks -validity 36500 -deststoretype pkcs12
security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:/wazx-jwt-store.jks
        key-alias: wazx-jwt
        key-password: bccfcsuknfxmecbh
        key-store-password: bccfcsuknfxmecbh